# Generated by Django 2.2.5 on 2019-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto_Turistico',
            fields=[
                ('idPonto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=1000, null=True)),
                ('categoria', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
            options={
                'ordering': ['idPonto'],
            },
        ),
    ]
