# Generated by Django 2.2.5 on 2019-09-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ponto_Turistico',
            new_name='PontoTuristico',
        ),
    ]
